version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "test echo for demo!"
  test:
    docker:
      - image: cimg/base:edge
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "This is the first test statement"
      - run: echo "This is the second test statement"
      - run: echo "This is the third test statement"
      - run: echo "this is an addition test for a live demo!"
      -run: echo "This will be an error!"

workflows:
  build_and_test:
    jobs:
      - build:
          context:
          - docker username
          - docker password
      - test:
          context:
            - docker username
            - docker password