version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
          - docker username
          - docker password

jobs:
  build:
    docker:
      - image: cimg/base:edge
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "test echo for demo!"